### ISSUE TITLE
Unable to run example in README

### ISSUE THREAD

**Issue by jamesrachlin** [DiameterHealth/cpcds-converter#3]
I followed the README instructions to load the CPCDS sample CSV into HAPI and I am getting an error. Main message of the error is this:

Exception in thread "main" ca.uhn.fhir.rest.server.exceptions.UnprocessableEntityException: HTTP 422 Unprocessable Entity: Invalid reference found at path 'ExplanationOfBenefit.payee.party'. Resource type 'null' is not valid for this path

Full error is below, including the command I ran. I confirmed that I successfully generated a sample CPCDS CSV file using Synthea and I confirmed that the HAPI server is up and running. I've tried running with Java 8 and Java 11. You can see it starts the converter and then when it attempts to write to the HAPI server, the process stops because of the "resource type null" error.

Jamess-MacBook-Pro:cpcds-converter jrachlin$ gradle execute --args="-i /Users/jrachlin/synthea/output/cpcds/CPCDS_Claims.csv -f http://localhost:8080/hapi-fhir-jpaserver/fhir"

> Task :execute
Starting converter at 2020-08-27T15:24:04.848Z
Loading from: /Users/jrachlin/synthea/output/cpcds/CPCDS_Claims.csv
Loading to: http://localhost:8080/hapi-fhir-jpaserver/fhir
Delay by: null
Mapping for Claim: 66827fcb-4a99-08ff-e338-f001c31e17da at 2020-08-27T15:24:04.884Z
Mapping for Claim: e2092686-b027-5290-0138-852d8e8cb515 at 2020-08-27T15:24:04.895Z
Mapping for Claim: e2092686-b027-5290-0138-852d8e8cb515 at 2020-08-27T15:24:04.896Z
Mapping for Claim: 5fd064f3-dd40-824c-7e4c-1e700ad87ccb at 2020-08-27T15:24:04.896Z
Mapping for Claim: 117085ca-d9c1-0f83-756d-69ac261bb297 at 2020-08-27T15:24:04.896Z
Mapping for Claim: fbf924e5-5394-fff6-0237-6b37d96e1042 at 2020-08-27T15:24:04.896Z
Mapping for Claim: fbf924e5-5394-fff6-0237-6b37d96e1042 at 2020-08-27T15:24:04.897Z
Mapping for Claim: 7025b220-970a-7256-b2a7-af3ccea62634 at 2020-08-27T15:24:04.897Z
Mapping for Claim: 7025b220-970a-7256-b2a7-af3ccea62634 at 2020-08-27T15:24:04.897Z
Mapping for Claim: 7025b220-970a-7256-b2a7-af3ccea62634 at 2020-08-27T15:24:04.897Z
Mapping for Claim: 7025b220-970a-7256-b2a7-af3ccea62634 at 2020-08-27T15:24:04.897Z
Mapping for Claim: f4dd052c-f8d9-7a6e-4803-5ed731f7dde6 at 2020-08-27T15:24:04.898Z
Mapping for Claim: f4dd052c-f8d9-7a6e-4803-5ed731f7dde6 at 2020-08-27T15:24:04.898Z
Mapping for Claim: f4dd052c-f8d9-7a6e-4803-5ed731f7dde6 at 2020-08-27T15:24:04.898Z
Mapping for Claim: f4dd052c-f8d9-7a6e-4803-5ed731f7dde6 at 2020-08-27T15:24:04.898Z
Mapping for Claim: 44ff5de9-195f-1520-c252-cef6d8cdc404 at 2020-08-27T15:24:04.898Z
Mapping for Claim: d2a3f641-e466-2e12-9456-882915981c41 at 2020-08-27T15:24:04.898Z
Mapping for Claim: d2a3f641-e466-2e12-9456-882915981c41 at 2020-08-27T15:24:04.898Z
Mapping for Claim: 01f231c4-54d0-681b-ab8a-a37d894dec9f at 2020-08-27T15:24:04.899Z
Mapping for Claim: 01f231c4-54d0-681b-ab8a-a37d894dec9f at 2020-08-27T15:24:04.899Z
Mapping for Claim: b6978c87-f9ae-a774-0bd8-75fea2c57ab8 at 2020-08-27T15:24:04.899Z
Mapping for Claim: 577bf4ab-8747-7e12-8902-86d9cd79453c at 2020-08-27T15:24:04.899Z
Mapping for Claim: 2c323ad9-37af-a83a-28c6-14446538a10a at 2020-08-27T15:24:04.899Z
Mapping for Claim: 2c323ad9-37af-a83a-28c6-14446538a10a at 2020-08-27T15:24:04.899Z
Mapping for Claim: 2c323ad9-37af-a83a-28c6-14446538a10a at 2020-08-27T15:24:04.899Z
Mapping for Claim: 2c323ad9-37af-a83a-28c6-14446538a10a at 2020-08-27T15:24:04.899Z
Mapping for Claim: 2c323ad9-37af-a83a-28c6-14446538a10a at 2020-08-27T15:24:04.900Z
Mapping for Claim: 2c323ad9-37af-a83a-28c6-14446538a10a at 2020-08-27T15:24:04.900Z
Mapping for Claim: 2c323ad9-37af-a83a-28c6-14446538a10a at 2020-08-27T15:24:04.900Z
Writing for Claim: 66827fcb-4a99-08ff-e338-f001c31e17da at 2020-08-27T15:24:04.901Z
Checked for EoB: claim-unique-identifier:66827fcb-4a99-08ff-e338-f001c31e17da at 2020-08-27T15:24:05.049Z
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Did not find existing
Exception in thread "main" ca.uhn.fhir.rest.server.exceptions.UnprocessableEntityException: HTTP 422 Unprocessable Entity: Invalid reference found at path 'ExplanationOfBenefit.payee.party'. Resource type 'null' is not valid for this path
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at ca.uhn.fhir.rest.server.exceptions.BaseServerResponseException.newInstance(BaseServerResponseException.java:302)
        at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:351)
        at ca.uhn.fhir.rest.client.impl.GenericClient$BaseClientExecutable.invoke(GenericClient.java:434)
        at ca.uhn.fhir.rest.client.impl.GenericClient$CreateInternal.execute(GenericClient.java:581)
        at ca.uhn.fhir.rest.client.impl.GenericClient$CreateInternal.execute(GenericClient.java:536)
        at com.diameterhealth.cpcds.HapiExplanationOfBenefitsFHIRSourceAdapter.create(HapiExplanationOfBenefitsFHIRSourceAdapter.kt:43)
        at com.diameterhealth.cpcds.HapiExplanationOfBenefitsFHIRSourceAdapter.create(HapiExplanationOfBenefitsFHIRSourceAdapter.kt:18)
        at com.diameterhealth.cpcds.CPCDSWriterKt.writeRow(CPCDSWriter.kt:34)
        at com.diameterhealth.cpcds.ConverterKt.convert(Converter.kt:42)
        at com.diameterhealth.cpcds.ConverterKt.main(Converter.kt:35)

> Task :execute FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':execute'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by samschifman** [comment]
Hi @jamesrachlin,

Apologies for the delayed response. 

The Hapi server you are using must be set up to be stricter then the one I tested with. I believe the issue is that I was unsure what type of resource was being referenced by the payee. Is seems most likely that it should be a Patient, but I was could not be certain. If you know, this problem can be fixed by passing the correct `ResourceType` as the second parameter at line 214 of `CPCDSToFHIRMapper.kt`. 

As I indicated, the parser in the Hapi server I was testing with didn't prevent me from posting with a missing value there. The server you are using is correct to complain. 

If you can submit the answer back to the project that would obviously be appreciated. 

Regards,

**Comment by itsismail** [comment]
Hi @jamesrachlin  @samschifman 
Did you folks found any work around to fix the above mentioned bug
